//! Protobuf types for the Substreams Solana block model.
//!
//! Generated by `buf generate`; see `buf.gen.yaml`.

pub mod sf {
    pub mod solana {
        pub mod r#type {
            pub mod v1 {
                include!("sf.solana.type.v1.mod.rs");
            }
        }
    }
}
