// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.solana.type.v1.account.rs");
include!("sf.solana.type.v1.type.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.solana.type.v1.account.__view.rs");
        include!("sf.solana.type.v1.type.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.solana.type.v1.account.__lazy_view.rs");
        include!("sf.solana.type.v1.type.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::AccountBlockView;
#[doc(inline)]
pub use self::__buffa::view::AccountBlockOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::AccountBlockLazyView;
#[doc(inline)]
pub use self::__buffa::view::AccountView;
#[doc(inline)]
pub use self::__buffa::view::AccountOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::AccountLazyView;
#[doc(inline)]
pub use self::__buffa::view::BlockView;
#[doc(inline)]
pub use self::__buffa::view::BlockOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockLazyView;
#[doc(inline)]
pub use self::__buffa::view::ConfirmedTransactionView;
#[doc(inline)]
pub use self::__buffa::view::ConfirmedTransactionOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ConfirmedTransactionLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionView;
#[doc(inline)]
pub use self::__buffa::view::TransactionOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionLazyView;
#[doc(inline)]
pub use self::__buffa::view::MessageView;
#[doc(inline)]
pub use self::__buffa::view::MessageOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::MessageLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionConfigView;
#[doc(inline)]
pub use self::__buffa::view::TransactionConfigOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionConfigLazyView;
#[doc(inline)]
pub use self::__buffa::view::MessageHeaderView;
#[doc(inline)]
pub use self::__buffa::view::MessageHeaderOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::MessageHeaderLazyView;
#[doc(inline)]
pub use self::__buffa::view::MessageAddressTableLookupView;
#[doc(inline)]
pub use self::__buffa::view::MessageAddressTableLookupOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::MessageAddressTableLookupLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionStatusMetaView;
#[doc(inline)]
pub use self::__buffa::view::TransactionStatusMetaOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionStatusMetaLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionErrorView;
#[doc(inline)]
pub use self::__buffa::view::TransactionErrorOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionErrorLazyView;
#[doc(inline)]
pub use self::__buffa::view::InnerInstructionsView;
#[doc(inline)]
pub use self::__buffa::view::InnerInstructionsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::InnerInstructionsLazyView;
#[doc(inline)]
pub use self::__buffa::view::InnerInstructionView;
#[doc(inline)]
pub use self::__buffa::view::InnerInstructionOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::InnerInstructionLazyView;
#[doc(inline)]
pub use self::__buffa::view::CompiledInstructionView;
#[doc(inline)]
pub use self::__buffa::view::CompiledInstructionOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CompiledInstructionLazyView;
#[doc(inline)]
pub use self::__buffa::view::TokenBalanceView;
#[doc(inline)]
pub use self::__buffa::view::TokenBalanceOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TokenBalanceLazyView;
#[doc(inline)]
pub use self::__buffa::view::UiTokenAmountView;
#[doc(inline)]
pub use self::__buffa::view::UiTokenAmountOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::UiTokenAmountLazyView;
#[doc(inline)]
pub use self::__buffa::view::ReturnDataView;
#[doc(inline)]
pub use self::__buffa::view::ReturnDataOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ReturnDataLazyView;
#[doc(inline)]
pub use self::__buffa::view::RewardView;
#[doc(inline)]
pub use self::__buffa::view::RewardOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RewardLazyView;
#[doc(inline)]
pub use self::__buffa::view::RewardsView;
#[doc(inline)]
pub use self::__buffa::view::RewardsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RewardsLazyView;
#[doc(inline)]
pub use self::__buffa::view::UnixTimestampView;
#[doc(inline)]
pub use self::__buffa::view::UnixTimestampOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::UnixTimestampLazyView;
#[doc(inline)]
pub use self::__buffa::view::BlockHeightView;
#[doc(inline)]
pub use self::__buffa::view::BlockHeightOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockHeightLazyView;
