// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/solana/type/v1/account.proto

#[derive(Clone, Debug, Default)]
pub struct AccountBlockView<'a> {
    /// Field 1: `slot`
    pub slot: u64,
    /// Field 2: `hash`
    pub hash: &'a str,
    /// Field 3: `parent_slot`
    pub parent_slot: u64,
    /// Field 4: `parent_hash`
    pub parent_hash: &'a str,
    /// Field 6: `timestamp`
    pub timestamp: ::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'a>,
    >,
    /// Field 7: `accounts`
    pub accounts: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::AccountView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for AccountBlockView<'a> {
    type Owned = super::super::AccountBlock;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.slot = ::buffa::types::decode_uint64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.parent_slot = ::buffa::types::decode_uint64(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.parent_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.timestamp.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.timestamp = ::buffa::MessageFieldView::set(
                            <::buffa_types::google::protobuf::__buffa::view::TimestampView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::AccountView>(),
                )?;
                view.accounts
                    .push(
                        <super::super::__buffa::view::AccountView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::AccountBlock, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::AccountBlock, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::AccountBlock {
            slot: self.slot,
            hash: self.hash.to_string(),
            parent_slot: self.parent_slot,
            parent_hash: self.parent_hash.to_string(),
            timestamp: match self.timestamp.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::buffa_types::google::protobuf::Timestamp,
                        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            accounts: self
                .accounts
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for AccountBlockView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.slot != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.slot) as u64;
        }
        if !self.hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hash) as u64;
        }
        if self.parent_slot != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.parent_slot) as u64;
        }
        if !self.parent_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.parent_hash) as u64;
        }
        if self.timestamp.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.timestamp.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.accounts {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.slot != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.slot, buf);
        }
        if !self.hash.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.hash, buf);
        }
        if self.parent_slot != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.parent_slot, buf);
        }
        if !self.parent_hash.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.parent_hash, buf);
        }
        if self.timestamp.is_set() {
            ::buffa::types::put_len_delimited_header(
                6u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.timestamp.write_to(__cache, buf);
        }
        for v in &self.accounts {
            ::buffa::types::put_len_delimited_header(
                7u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for AccountBlockView<'a> {
    const PACKAGE: &'static str = "sf.solana.type.v1";
    const NAME: &'static str = "AccountBlock";
    const FULL_NAME: &'static str = "sf.solana.type.v1.AccountBlock";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.solana.type.v1.AccountBlock";
}
::buffa::impl_default_view_instance!(AccountBlockView);
::buffa::impl_view_reborrow!(AccountBlockView);
/** Self-contained, `'static` owned view of a `AccountBlock` message.

 Wraps [`::buffa::OwnedView`]`<`[`AccountBlockView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`AccountBlockView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct AccountBlockOwnedView(::buffa::OwnedView<AccountBlockView<'static>>);
impl AccountBlockOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            AccountBlockOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            AccountBlockOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::AccountBlock,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            AccountBlockOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`AccountBlockView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &AccountBlockView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::AccountBlock {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `slot`
    #[must_use]
    pub fn slot(&self) -> u64 {
        self.0.reborrow().slot
    }
    /// Field 2: `hash`
    #[must_use]
    pub fn hash(&self) -> &'_ str {
        self.0.reborrow().hash
    }
    /// Field 3: `parent_slot`
    #[must_use]
    pub fn parent_slot(&self) -> u64 {
        self.0.reborrow().parent_slot
    }
    /// Field 4: `parent_hash`
    #[must_use]
    pub fn parent_hash(&self) -> &'_ str {
        self.0.reborrow().parent_hash
    }
    /// Field 6: `timestamp`
    #[must_use]
    pub fn timestamp(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().timestamp
    }
    /// Field 7: `accounts`
    #[must_use]
    pub fn accounts(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::AccountView<'_>> {
        &self.0.reborrow().accounts
    }
}
impl ::core::convert::From<::buffa::OwnedView<AccountBlockView<'static>>>
for AccountBlockOwnedView {
    fn from(inner: ::buffa::OwnedView<AccountBlockView<'static>>) -> Self {
        AccountBlockOwnedView(inner)
    }
}
impl ::core::convert::From<AccountBlockOwnedView>
for ::buffa::OwnedView<AccountBlockView<'static>> {
    fn from(wrapper: AccountBlockOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<AccountBlockView<'static>>>
for AccountBlockOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<AccountBlockView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::AccountBlock {
    type View<'a> = AccountBlockView<'a>;
    type ViewHandle = AccountBlockOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct AccountView<'a> {
    /// Field 1: `address`
    pub address: &'a [u8],
    /// Field 2: `owner`
    pub owner: &'a [u8],
    /// Field 3: `data`
    pub data: &'a [u8],
    /// Field 7: `deleted`
    pub deleted: bool,
}
impl<'a> ::buffa::MessageView<'a> for AccountView<'a> {
    type Owned = super::super::Account;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.address = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.owner = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.data = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.deleted = ::buffa::types::decode_bool(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Account, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Account, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Account {
            address: (self.address).to_vec(),
            owner: (self.owner).to_vec(),
            data: (self.data).to_vec(),
            deleted: self.deleted,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for AccountView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.address.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.address) as u64;
        }
        if !self.owner.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.owner) as u64;
        }
        if !self.data.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.data) as u64;
        }
        if self.deleted {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.address.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.address, buf);
        }
        if !self.owner.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.owner, buf);
        }
        if !self.data.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.data, buf);
        }
        if self.deleted {
            ::buffa::types::put_bool_field(7u32, self.deleted, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for AccountView<'a> {
    const PACKAGE: &'static str = "sf.solana.type.v1";
    const NAME: &'static str = "Account";
    const FULL_NAME: &'static str = "sf.solana.type.v1.Account";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.solana.type.v1.Account";
}
::buffa::impl_default_view_instance!(AccountView);
::buffa::impl_view_reborrow!(AccountView);
/** Self-contained, `'static` owned view of a `Account` message.

 Wraps [`::buffa::OwnedView`]`<`[`AccountView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`AccountView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct AccountOwnedView(::buffa::OwnedView<AccountView<'static>>);
impl AccountOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(AccountOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            AccountOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Account,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            AccountOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`AccountView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &AccountView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Account {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `address`
    #[must_use]
    pub fn address(&self) -> &'_ [u8] {
        self.0.reborrow().address
    }
    /// Field 2: `owner`
    #[must_use]
    pub fn owner(&self) -> &'_ [u8] {
        self.0.reborrow().owner
    }
    /// Field 3: `data`
    #[must_use]
    pub fn data(&self) -> &'_ [u8] {
        self.0.reborrow().data
    }
    /// Field 7: `deleted`
    #[must_use]
    pub fn deleted(&self) -> bool {
        self.0.reborrow().deleted
    }
}
impl ::core::convert::From<::buffa::OwnedView<AccountView<'static>>>
for AccountOwnedView {
    fn from(inner: ::buffa::OwnedView<AccountView<'static>>) -> Self {
        AccountOwnedView(inner)
    }
}
impl ::core::convert::From<AccountOwnedView>
for ::buffa::OwnedView<AccountView<'static>> {
    fn from(wrapper: AccountOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<AccountView<'static>>>
for AccountOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<AccountView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Account {
    type View<'a> = AccountView<'a>;
    type ViewHandle = AccountOwnedView;
}
