// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/solana/type/v1/account.proto

#[derive(Clone, PartialEq, Default)]
pub struct AccountBlock {
    /// Field 1: `slot`
    pub slot: u64,
    /// Field 2: `hash`
    pub hash: ::buffa::alloc::string::String,
    /// Field 3: `parent_slot`
    pub parent_slot: u64,
    /// Field 4: `parent_hash`
    pub parent_hash: ::buffa::alloc::string::String,
    /// Field 6: `timestamp`
    pub timestamp: ::buffa::MessageField<
        ::buffa_types::google::protobuf::Timestamp,
        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
    >,
    /// Field 7: `accounts`
    pub accounts: ::buffa::alloc::vec::Vec<Account>,
}
impl ::core::fmt::Debug for AccountBlock {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("AccountBlock")
            .field("slot", &self.slot)
            .field("hash", &self.hash)
            .field("parent_slot", &self.parent_slot)
            .field("parent_hash", &self.parent_hash)
            .field("timestamp", &self.timestamp)
            .field("accounts", &self.accounts)
            .finish()
    }
}
impl AccountBlock {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.solana.type.v1.AccountBlock";
}
::buffa::impl_default_instance!(AccountBlock);
impl ::buffa::MessageName for AccountBlock {
    const PACKAGE: &'static str = "sf.solana.type.v1";
    const NAME: &'static str = "AccountBlock";
    const FULL_NAME: &'static str = "sf.solana.type.v1.AccountBlock";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.solana.type.v1.AccountBlock";
}
impl ::buffa::Message for AccountBlock {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.slot != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.slot) as u64;
        }
        if !self.hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hash) as u64;
        }
        if self.parent_slot != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.parent_slot) as u64;
        }
        if !self.parent_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.parent_hash) as u64;
        }
        if self.timestamp.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.timestamp.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.accounts {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.slot != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.slot, buf);
        }
        if !self.hash.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.hash, buf);
        }
        if self.parent_slot != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.parent_slot, buf);
        }
        if !self.parent_hash.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.parent_hash, buf);
        }
        if self.timestamp.is_set() {
            ::buffa::types::put_len_delimited_header(
                6u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.timestamp.write_to(__cache, buf);
        }
        for v in &self.accounts {
            ::buffa::types::put_len_delimited_header(
                7u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.slot = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.hash, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.parent_slot = ::buffa::types::decode_uint64(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.parent_hash, buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.timestamp.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.accounts.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.slot = 0u64;
        self.hash.clear();
        self.parent_slot = 0u64;
        self.parent_hash.clear();
        self.timestamp = ::buffa::MessageField::none();
        self.accounts.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Account {
    /// Field 1: `address`
    pub address: ::buffa::alloc::vec::Vec<u8>,
    /// Field 2: `owner`
    pub owner: ::buffa::alloc::vec::Vec<u8>,
    /// Field 3: `data`
    pub data: ::buffa::alloc::vec::Vec<u8>,
    /// Field 7: `deleted`
    pub deleted: bool,
}
impl ::core::fmt::Debug for Account {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Account")
            .field("address", &self.address)
            .field("owner", &self.owner)
            .field("data", &self.data)
            .field("deleted", &self.deleted)
            .finish()
    }
}
impl Account {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.solana.type.v1.Account";
}
::buffa::impl_default_instance!(Account);
impl ::buffa::MessageName for Account {
    const PACKAGE: &'static str = "sf.solana.type.v1";
    const NAME: &'static str = "Account";
    const FULL_NAME: &'static str = "sf.solana.type.v1.Account";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.solana.type.v1.Account";
}
impl ::buffa::Message for Account {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.address.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.address) as u64;
        }
        if !self.owner.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.owner) as u64;
        }
        if !self.data.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.data) as u64;
        }
        if self.deleted {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.address.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.address, buf);
        }
        if !self.owner.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.owner, buf);
        }
        if !self.data.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.data, buf);
        }
        if self.deleted {
            ::buffa::types::put_bool_field(7u32, self.deleted, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.address, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.owner, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.data, buf)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.deleted = ::buffa::types::decode_bool(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.address.clear();
        self.owner.clear();
        self.data.clear();
        self.deleted = false;
    }
}
